# Generated by Django 2.2.7 on 2019-12-18 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191218_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='status',
        ),
        migrations.AddField(
            model_name='reward',
            name='redeem_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uservendor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
