# Generated by Django 2.2.7 on 2019-12-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191218_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='user',
            new_name='staff',
        ),
    ]
