# Generated by Django 2.2.7 on 2019-12-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191219_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.Card'),
        ),
    ]
