# Generated by Django 2.2.7 on 2019-12-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191219_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='redeem_date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='redeemed',
        ),
    ]
