# Generated by Django 2.2.7 on 2019-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191224_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('cafe', 'cafe'), ('donut', 'donut')], max_length=105, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images'),
        ),
    ]
