# Generated by Django 2.2.7 on 2019-12-30 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191229_2030'),
        ('api', '0008_auto_20191230_1344'),
    ]

    operations = [
    ]
